theme = "lynx"
title = "yzawa"
baseURL = 'https://yzawa.me/'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Yasuzawa, Mikichika"
  headline = "A Japanese College Student"
  image = "logo.webp"
  links = [
    { github = "https://github.com/yszwa/" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"