theme = "lynx"
title = "Lynx"
baseURL = 'https://yzawa.me/'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Lynx"
  headline = "A simple links theme for Hugo built with Tailwind CSS"
  # image = "author.jpg"
  links = [
    { github = "https://github.com/yszwa/" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"